[package]
name = "objects"
version = "0.0.1"
edition = "2021"

[dependencies]
base64 = "0.13"
cucumber = "0.13"
hmac = "0.10"
reqwest = { version = "0.11", features = ["json"] }
sha2 = "0.9.2"
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1" }
urlencoding = "2.1.0"